// Copyright 1998-2018 Epic Games, Inc. All Rights Reserved.

#pragma once

DEFINE_ERROR_CODE(EC_NONE, 0, "")
DEFINE_ERROR_CODE(EC_NETWORKERROR, 6, "")
DEFINE_ERROR_CODE(EC_PASSWORDERROR, 202, "密码错误")
DEFINE_ERROR_CODE(EC_INVALIDDATA, 400, "非法数据")
DEFINE_ERROR_CODE(EC_UNKNOWNERROR, 404, "未知错误")