// Copyright 1998-2018 Epic Games, Inc. All Rights Reserved.

#pragma once


DEFINE_LOGIC_CODE(LC_INVALID, 0, "")
DEFINE_LOGIC_CODE(LC_CONNECTION, 200, "网络连接")
DEFINE_LOGIC_CODE(LC_REGISTERSERVER, 20001, "注册服务器")
DEFINE_LOGIC_CODE(LC_MATCHSTATE, 20002, "游戏状态")
DEFINE_LOGIC_CODE(LC_NUMPLAYERS, 20003, "房间人数")
DEFINE_LOGIC_CODE(LC_USERLOGIN, 10000, "用户登录")
DEFINE_LOGIC_CODE(LC_INVITATION, 10001, "邀请队友")
DEFINE_LOGIC_CODE(LC_MATCHGAME, 10002, "匹配游戏")
DEFINE_LOGIC_CODE(LC_CANCELMATCH, 10003, "取消匹配")
DEFINE_LOGIC_CODE(LC_CLIENTTRAVEL, 10003, "客户端进入地图")