// Copyright 1998-2018 Epic Games, Inc. All Rights Reserved.

#pragma once


DEFINE_LOGIC_CODE(INVALID, 0, "")
DEFINE_LOGIC_CODE(CONNECTION, 200, "网络连接")
DEFINE_LOGIC_CODE(REGISTER_SERVER, 20001, "注册服务器")
DEFINE_LOGIC_CODE(USER_LOGIN, 10000, "用户登录")
DEFINE_LOGIC_CODE(INVITATION, 10001, "邀请队友")
DEFINE_LOGIC_CODE(MATCH_GAME, 10002, "匹配游戏")